Update some dependencies to latest
IMGARENA/streams-service-generator pull request #8
Opened 2023-10-30 15:49 UTC by matghunter

2023-10-31 10:57 UTC, ASarco requested changes

2023-10-31 10:57 UTC, ASarco commented on {{ project_slug }}/.github/workflows/main-test-release.yaml
> +          ./mvn -B spring-boot:build-image -DskipTests=true -Drevision={{ "${{ needs.test_release.outputs.new-release-version }}" }}
Should be ./mvnw here?

2023-10-31 11:03 UTC, ASarco approved these changes

2023-11-06 10:07 UTC, marylo-imgarena approved these changes

2023-11-06 10:19 UTC, merged